import type { Course } from "@/types";

export const courses: Course[] = [
  {
    id: "corte-profissional",
    name: "Corte Profissional",
    description:
      "Domine as técnicas de corte masculino do básico ao avançado. Tesoura, máquina, degradê, texturização e finalização. Curso completo para barbeiros iniciantes e intermediários.",
    icon: "Scissors",
    image: "/images/gallery/gallery-2.jpg",
    duration: "4 semanas",
    level: "Iniciante",
    modules: 12,
    instructor: "Bilico",
    status: "Em andamento",
    href: "https://wa.me/5515996828034?text=Ol%C3%A1!%20Tenho%20interesse%20no%20curso%20de%20Corte%20Profissional.%20Poderia%20me%20dar%20mais%20informa%C3%A7%C3%B5es%3F",
  },
  {
    id: "barba-e-modelagem",
    name: "Barba & Modelagem",
    description:
      "Aprenda a arte da barbearia clássica: navalha, toalha quente, modelagem de barba, bigode e acabamento perfeito. Técnicas tradicionais com toque moderno.",
    icon: "Ruler",
    image: "/images/gallery/gallery-3.jpg",
    duration: "3 semanas",
    level: "Iniciante",
    modules: 8,
    instructor: "Bilico",
    status: "Em andamento",
    href: "https://wa.me/5515996828034?text=Ol%C3%A1!%20Tenho%20interesse%20no%20curso%20de%20Barba%20e%20Modelagem.%20Poderia%20me%20dar%20mais%20informa%C3%A7%C3%B5es%3F",
  },
  {
    id: "degrade-avancado",
    name: "Degradê Avançado",
    description:
      "Do skin fade ao drop fade, passando por mid fade, taper fade e degradê social. Técnicas avançadas de transição, textura e desenho para barbeiros experientes.",
    icon: "FlipVertical",
    image: "/images/gallery/gallery-1.jpg",
    duration: "4 semanas",
    level: "Avançado",
    modules: 10,
    instructor: "Bilico",
    status: "Em breve",
    href: "https://wa.me/5515996828034?text=Ol%C3%A1!%20Tenho%20interesse%20no%20curso%20de%20Degrad%C3%AA%20Avan%C3%A7ado.%20Poderia%20me%20dar%20mais%20informa%C3%A7%C3%B5es%3F",
  },
  {
    id: "trancas-e-dreads",
    name: "Tranças & Dreads",
    description:
      "Curso completo de tranças estilizadas: nagô, box braids, twists, twists torcidos e dreads. Da instalação à manutenção, com técnicas profissionais.",
    icon: "Zap",
    image: "/images/gallery/gallery-4.jpg",
    duration: "5 semanas",
    level: "Intermediário",
    modules: 14,
    instructor: "Bilico",
    status: "Em breve",
    href: "https://wa.me/5515996828034?text=Ol%C3%A1!%20Tenho%20interesse%20no%20curso%20de%20Tran%C3%A7as%20e%20Dreads.%20Poderia%20me%20dar%20mais%20informa%C3%A7%C3%B5es%3F",
  },
  {
    id: "tratamentos-capilares",
    name: "Tratamentos Capilares",
    description:
      "Hidratação, reconstrução e nutrição capilar. Aprenda a identificar tipos de cabelo, usar produtos profissionais e oferecer tratamentos revitalizantes.",
    icon: "Droplets",
    image: "/images/gallery/gallery-6.jpg",
    duration: "3 semanas",
    level: "Intermediário",
    modules: 9,
    instructor: "Bilico",
    status: "Em breve",
    href: "https://wa.me/5515996828034?text=Ol%C3%A1!%20Tenho%20interesse%20no%20curso%20de%20Tratamentos%20Capilares.%20Poderia%20me%20dar%20mais%20informa%C3%A7%C3%B5es%3F",
  },
  {
    id: "gestao-barbearia",
    name: "Gestão de Barbearia",
    description:
      "Empreenda no mundo da barbearia: finanças, marketing digital, fidelização de clientes, precificação de serviços e gestão de agenda. Transforme sua arte em negócio.",
    icon: "BarChart3",
    image: "/images/gallery/gallery-8.jpg",
    duration: "6 semanas",
    level: "Iniciante",
    modules: 16,
    instructor: "Bilico",
    status: "Em breve",
    href: "https://wa.me/5515996828034?text=Ol%C3%A1!%20Tenho%20interesse%20no%20curso%20de%20Gest%C3%A3o%20de%20Barbearia.%20Poderia%20me%20dar%20mais%20informa%C3%A7%C3%B5es%3F",
  },
];
